[package]
name = "fluent_python_rs"
version = "0.1.0"
edition = "2021"

[lib]
name = "fluent_python_rs"
path = "src/lib.rs"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
rand = "0.8"
thiserror = "1.0"

[dev-dependencies]
criterion = "0.5"
